Adding admin-page
makrenka/library pull request #4
Opened 2023-07-23 14:05 UTC by makrenka

2023-08-23 08:55 UTC, Gaurrus requested changes

2023-08-23 08:55 UTC, Gaurrus commented on src/components/admin-card-user/admin-card-user.tsx
> +    } = props;
nit: Так тоже хорошо, но еще круче и красивее доставать сразу на 21 строчке 😄

2023-08-23 08:55 UTC, Gaurrus commented on src/components/admin-card-user/admin-card-user.module.scss
> +.card {
https://github.com/makrenka/library/assets/85307211/7dc9465d-3280-418b-8cae-f882e54b68d6
Попробуй сделать чтобы этого прыжкуа не было при открытии

2023-08-23 08:55 UTC, Gaurrus commented on src/components/admin-card-user/admin-card-user.module.scss
> +    display: grid;
![image](https://github.com/makrenka/library/assets/85307211/336e2477-af25-48a5-bd67-f2a51c133d2f)
не нашел где перейти на админскую страницу

2023-08-23 08:57 UTC, ValadzkoAliaksei commented on src/components/admin-card-user/admin-card-user.module.scss
> +    display: grid;
что бы перейти на админскую страницу, надо зайти за админа)

2023-08-23 09:03 UTC, Gaurrus commented on src/components/admin-card-user/admin-card-user.module.scss
> +    display: grid;
ну роли есть у пользователя, я же скинул с network специально

2023-08-23 13:00 UTC, makrenka commented on src/components/admin-card-user/admin-card-user.module.scss
> +    display: grid;
путь '/admin' прописать)

2023-08-23 13:03 UTC, Gaurrus commented on src/components/admin-card-user/admin-card-user.module.scss
> +    display: grid;
сделай или в меню слева админку или в выподощем где пользователь справа - и чтобы видно было только когда есть права админа

2023-08-29 14:26 UTC, Gaurrus requested changes

2023-08-29 14:26 UTC, Gaurrus commented on src/components/admin-card-user/assets/return-sign-bgr-green.svg
вот эти картинки давай сделаем CSS-ом

2023-08-29 14:26 UTC, Gaurrus commented on src/components/admin-menu/assets/icon-close.svg
крестик тоже можно CSS-ом, если он отдельностоящий

2023-08-30 11:25 UTC, Gaurrus approved these changes

2023-08-30 12:07 UTC, merged